-- Run this in the Supabase SQL Editor to create tables and RLS.
-- Every entry and location is tied to the signed-in user (user_id).
-- Only that user can see or change their data; no one can see other users' entries or locations.

-- =============================================================================
-- LOCATIONS: one row per (user, location name). Each user only sees their own.
-- =============================================================================
create table if not exists public.locations (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete cascade not null,
  name text not null,
  unique(user_id, name)
);

alter table public.locations enable row level security;

create policy "Users can manage own locations"
  on public.locations for all
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

-- =============================================================================
-- INVENTORY ENTRIES: each row belongs to one user. Only that user can see/edit.
-- =============================================================================
create table if not exists public.inventory_entries (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete cascade not null,
  location_id bigint not null references public.locations(id) on delete restrict,
  name text not null,
  description text,
  image_path text,
  created_at timestamptz default now()
);

alter table public.inventory_entries enable row level security;

create policy "Users can read own entries"
  on public.inventory_entries for select
  using (auth.uid() = user_id);

create policy "Users can insert own entries"
  on public.inventory_entries for insert
  with check (auth.uid() = user_id);

create policy "Users can update own entries"
  on public.inventory_entries for update
  using (auth.uid() = user_id);

create policy "Users can delete own entries"
  on public.inventory_entries for delete
  using (auth.uid() = user_id);

create index if not exists inventory_entries_user_id_idx on public.inventory_entries(user_id);
create index if not exists inventory_entries_location_id_idx on public.inventory_entries(location_id);
create index if not exists locations_user_id_idx on public.locations(user_id);

-- =============================================================================
-- STORAGE (user-images): entry photos. Users can only upload/read their own folder.
-- Create bucket "user-images" in Storage first; then run the policies below.
-- =============================================================================
-- Allow users to upload only to their own folder (path = user_id/...)
create policy "Users can upload own images"
  on storage.objects for insert
  to authenticated
  with check (
    bucket_id = 'user-images'
    and (storage.foldername(name))[1] = auth.uid()::text
  );

-- Allow users to read only their own folder
create policy "Users can read own images"
  on storage.objects for select
  to authenticated
  using (
    bucket_id = 'user-images'
    and (storage.foldername(name))[1] = auth.uid()::text
  );

-- Allow users to delete only their own folder
create policy "Users can delete own images"
  on storage.objects for delete
  to authenticated
  using (
    bucket_id = 'user-images'
    and (storage.foldername(name))[1] = auth.uid()::text
  );
