-- Run this in the Supabase SQL Editor to create the inventory table and RLS policies.
-- Storage bucket "user-images" is used for entry photos (create in Storage if needed).

create table if not exists public.inventory_entries (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete cascade not null,
  name text not null,
  description text,
  location text not null,
  image_path text,
  created_at timestamptz default now()
);

alter table public.inventory_entries enable row level security;

create policy "Users can read own entries"
  on public.inventory_entries for select
  using (auth.uid() = user_id);

create policy "Users can insert own entries"
  on public.inventory_entries for insert
  with check (auth.uid() = user_id);

create policy "Users can update own entries"
  on public.inventory_entries for update
  using (auth.uid() = user_id);

create policy "Users can delete own entries"
  on public.inventory_entries for delete
  using (auth.uid() = user_id);

-- Optional: index for listing by user and location
create index if not exists inventory_entries_user_id_idx on public.inventory_entries(user_id);
create index if not exists inventory_entries_location_idx on public.inventory_entries(user_id, location);
