-- Run this in the Supabase SQL Editor to create tables and RLS.
-- user_id references auth.users (Supabase auth). location_id references locations (your table).
-- Storage bucket "user-images" is used for entry photos (create in Storage if needed).

-- Locations: one row per (user, location name). Referenced by inventory_entries.
create table if not exists public.locations (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete cascade not null,
  name text not null,
  unique(user_id, name)
);

alter table public.locations enable row level security;

create policy "Users can manage own locations"
  on public.locations for all
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

-- Inventory entries: each row references one location (FK) and one user (FK via auth.users).
create table if not exists public.inventory_entries (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete cascade not null,
  location_id bigint not null references public.locations(id) on delete restrict,
  name text not null,
  description text,
  image_path text,
  created_at timestamptz default now()
);

alter table public.inventory_entries enable row level security;

create policy "Users can read own entries"
  on public.inventory_entries for select
  using (auth.uid() = user_id);

create policy "Users can insert own entries"
  on public.inventory_entries for insert
  with check (auth.uid() = user_id);

create policy "Users can update own entries"
  on public.inventory_entries for update
  using (auth.uid() = user_id);

create policy "Users can delete own entries"
  on public.inventory_entries for delete
  using (auth.uid() = user_id);

create index if not exists inventory_entries_user_id_idx on public.inventory_entries(user_id);
create index if not exists inventory_entries_location_id_idx on public.inventory_entries(location_id);
create index if not exists locations_user_id_idx on public.locations(user_id);
